### PR TITLE
Updated to honor default values provided in handler methods.

### PR DESCRIPTION
**Pull request by Vake93**
With this change the default values provided in the handler methods are applied if available

### CODE REVIEW

**Comment by davidfowl** [comment]
I guess this already works with the source generator?

**Comment by Vake93** [comment]
I've forgoten to check how this works with source generators. I've looked into now it and it seems `parameter.DefaultValue` throws a `NotImplementedException` when executing within the source generator. Tried to look up why it might be. Didnt find anything yet. Any ideas why it might be?

**Comment by davidfowl** [comment]
Because it's not implemented 😄 https://github.com/dotnet/runtime/blob/feae07921934805dc84d8d1c830b22008246b869/src/libraries/System.Private.CoreLib/src/System/Reflection/ParameterInfo.cs#L25. The ParameterWrapper needs to override that property and do something with it (https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.iparametersymbol.explicitdefaultvalue?view=roslyn-dotnet-3.9.0#Microsoft_CodeAnalysis_IParameterSymbol_ExplicitDefaultValue)

**Comment by Vake93** [comment]
@davidfowl Updated to handle  source generator scenario as well.

There is a lot of changers to handle it. Not sure if it’s the optimal way to do this. Let me know if you see any improvements that can be made.

**Comment by davidfowl** [comment]
Closing this since we've pivoted:

IfYouGIF

**Pull request closed without merging**
